Blog App | Create RSpec Files🎯
Rysth/RoR-Blog-App pull request #5
Opened 2023-10-30 18:47 UTC by Rysth

# 🏅 Features Implemented

List of things that were implemented based on the requirements:

## 📝 General requirements

- ✅ No Linters errors.
- ✅ Used GitFlow correctly.
- ✅ Created a professional `README` file.

## 📝 Project requirements

- ✅ Added RSpec as a gem to your project by using the gem `rspec-rails`.
- ✅ Created a Request spec file for all your controllers (PostsController, and UsersController).
- ✅ Checked the `status`, `template`, and `placeholder` text on each action (routes).

## 📷 Screenshots

### Results
![image](https://github.com/Rysth/RoR-Blog-App/assets/115722896/fee8b4fa-2bb5-43a4-b7ed-150353144c7a)

### RSpec UsersController
![code](https://github.com/Rysth/RoR-Blog-App/assets/115722896/65be9d59-a3be-4ec6-87ca-33fca6c4bbdb)

### RSpec PostsController
![code](https://github.com/Rysth/RoR-Blog-App/assets/115722896/c861ad0f-0b38-4508-810a-fd43753c952d)

[_John Palacios_](https://www.linkedin.com/in/john-palacios-rysthcraft/)
_RysthCraft_

2023-10-30 21:11 UTC, Gambit142 requested changes
Hi @Rysth 👋, 

Good job so far!

## Highlights
- Setup linters correctly ✔️ 
- Use of Rspec library to write tests ✔️ 
- Wrote requests spec tests for `Users` and `Posts` ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-10-30 21:11 UTC, Gambit142 commented on spec/requests/users_controller_spec.rb
> +end
- [ ] When I run your tests, some of them fail. Kindly see the screenshot attached below for further information.

![image](https://github.com/Rysth/RoR-Blog-App/assets/77106962/1c548bb8-d02b-422d-b38b-2bc91661ed11)

#### Please fix the tests and ensure that all of them pass. 👍 🖱️

2023-10-30 21:19 UTC, Rysth commented on spec/requests/posts_controller_spec.rb
> +end
Thanks!

2023-10-31 18:17 UTC, Rysth commented on spec/requests/users_controller_spec.rb
> +end
Done

2023-10-31 18:21 UTC, Rysth commented on spec/requests/users_controller_spec.rb
> +end
Done!

2023-10-31 18:31 UTC, Rysth commented on spec/requests/posts_controller_spec.rb
> +end
Done

2023-10-31 19:11 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Rysth, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- Rails migration errors have been successfully fix :wrench: :rocket: 
- All written tests passed :heavy_check_mark: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-31 19:11 UTC, FrederickMih commented on spec/requests/posts_controller_spec.rb
> +      expect(response.body).not_to be_nil
- [ ] Kindly check comment above. The `:show` template should be render correctly

2023-10-31 19:11 UTC, FrederickMih commented on spec/requests/posts_controller_spec.rb
> +      expect(response.body).not_to be_nil
- [ ] Kindly check above and fix :wrench: this issue please.

2023-10-31 20:08 UTC, Rysth commented on spec/requests/users_controller_spec.rb
> +      expect(response.body).not_to be_nil
Thanks

2023-10-31 20:41 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @Rysth, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="300px" />

## Highlights :heavy_check_mark: 
- [x] All unit tests are passing :white_check_mark: 
- [x] App uses the `rspec` ruby testing gem  :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Implemented all the changes from the previous reviewer :white_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-31 20:41 UTC, Felix45 commented on spec/controllers/posts_controller_spec.rb
- [ Good job ] Good job Implementing the changes from the previous reviewer :+1: all the tests are passing now.

![Screenshot from 2023-10-31 23-33-54](https://github.com/Rysth/RoR-Blog-App/assets/16392046/7b73dd4b-fbba-44c4-8f6b-0182ccf1884b)

2023-10-31 20:41 UTC, Rysth commented on spec/controllers/posts_controller_spec.rb
Thanks!

2023-10-31 20:41 UTC, merged